/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author LuckyRM
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        FlatIntelliJLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        temperaturaLabel = new javax.swing.JLabel();
        monedaLabel = new javax.swing.JLabel();
        masasLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        toggleTheme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 670, 430));

        menu.setBackground(new java.awt.Color(127, 44, 203));

        temperaturaLabel.setBackground(new java.awt.Color(127, 44, 203));
        temperaturaLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        temperaturaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperaturaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/temperature.png"))); // NOI18N
        temperaturaLabel.setText(" TEMPERATURA");
        temperaturaLabel.setOpaque(true);
        temperaturaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temperaturaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                temperaturaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                temperaturaLabelMouseExited(evt);
            }
        });

        monedaLabel.setBackground(new java.awt.Color(127, 44, 203));
        monedaLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        monedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monedaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        monedaLabel.setText(" MONEDAS         ");
        monedaLabel.setOpaque(true);
        monedaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monedaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monedaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monedaLabelMouseExited(evt);
            }
        });

        masasLabel.setBackground(new java.awt.Color(127, 44, 203));
        masasLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        masasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/weight.png"))); // NOI18N
        masasLabel.setText("  MASAS             ");
        masasLabel.setOpaque(true);
        masasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masasLabelMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONVERSOR");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(temperaturaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(masasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(monedaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(temperaturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(masasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(monedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 630));

        jPanel4.setBackground(new java.awt.Color(255, 132, 232));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 670, 160));

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerca.png"))); // NOI18N
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });
        jPanel1.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 30, 30));

        toggleTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toggle_off.png"))); // NOI18N
        toggleTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleThemeMouseClicked(evt);
            }
        });
        jPanel1.add(toggleTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        // TODO add your handling code here:
        exitLabel.setBackground(Color.red);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        // TODO add your handling code here:
        exitLabel.setBackground(Color.white);
    }//GEN-LAST:event_exitLabelMouseExited

    private void monedaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaLabelMouseEntered
        // TODO add your handling code here:
        monedaLabel.setBackground(Color.decode("#ff84e8"));

    }//GEN-LAST:event_monedaLabelMouseEntered

    private void monedaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaLabelMouseClicked
        // TODO add your handling code here:
        pageMonedas pageMonedas = new pageMonedas();
        showPanel(pageMonedas);
    }//GEN-LAST:event_monedaLabelMouseClicked

    private void temperaturaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaLabelMouseClicked
        // TODO add your handling code here:
        pageTemperatura pageTemperatura = new pageTemperatura();
        showPanel(pageTemperatura);
    }//GEN-LAST:event_temperaturaLabelMouseClicked

    private void masasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masasLabelMouseClicked
        // TODO add your handling code here:
        pageMasas pageMasas = new pageMasas();
        showPanel(pageMasas);
    }//GEN-LAST:event_masasLabelMouseClicked

    private void monedaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaLabelMouseExited
        // TODO add your handling code here:
        monedaLabel.setBackground(Color.decode("#7f2ccb"));
    }//GEN-LAST:event_monedaLabelMouseExited

    private void temperaturaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaLabelMouseEntered
        // TODO add your handling code here:
        temperaturaLabel.setBackground(Color.decode("#ff84e8"));
    }//GEN-LAST:event_temperaturaLabelMouseEntered

    private void temperaturaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaLabelMouseExited
        // TODO add your handling code here:
        temperaturaLabel.setBackground(Color.decode("#7f2ccb"));
    }//GEN-LAST:event_temperaturaLabelMouseExited

    private void masasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masasLabelMouseEntered
        // TODO add your handling code here:
        masasLabel.setBackground(Color.decode("#ff84e8"));
    }//GEN-LAST:event_masasLabelMouseEntered

    private void masasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masasLabelMouseExited
        // TODO add your handling code here:
        masasLabel.setBackground(Color.decode("#7f2ccb"));
    }//GEN-LAST:event_masasLabelMouseExited
    
    boolean darkMode = false;
    private void toggleThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleThemeMouseClicked
        // TODO add your handling code here:
        if(!darkMode){
            FlatAnimatedLafChange.showSnapshot();
            toggleTheme.setIcon(new ImageIcon(getClass().getResource("/img/toggle.png")));
            FlatDarculaLaf.setup();
            FlatLaf.updateUI();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();
            darkMode = true;
        } else {
            FlatAnimatedLafChange.showSnapshot();
            toggleTheme.setIcon(new ImageIcon(getClass().getResource("/img/toggle_off.png")));
            FlatIntelliJLaf.setup();
            FlatLaf.updateUI();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();
            darkMode = false;
        }
        
    }//GEN-LAST:event_toggleThemeMouseClicked
    
    private void showPanel(JPanel p){
        p.setSize(670,430);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel masasLabel;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel monedaLabel;
    private javax.swing.JLabel temperaturaLabel;
    private javax.swing.JLabel toggleTheme;
    // End of variables declaration//GEN-END:variables
}
