/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import logica.Logica;
import static logica.Logica.redondear;

/**
 *
 * @author LuckyRM
 */
public class pageMasas extends javax.swing.JPanel {

    /**
     * Creates new form pageDivisas
     */
    public pageMasas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMasas = new javax.swing.JPanel();
        Valor = new javax.swing.JTextField();
        cmbDe = new javax.swing.JComboBox<>();
        cmbA = new javax.swing.JComboBox<>();
        btnButton = new javax.swing.JPanel();
        txtButton = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        valorConvertido = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMasas.setPreferredSize(new java.awt.Dimension(670, 430));
        bgMasas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Valor.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        Valor.setText("12346");
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });
        bgMasas.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 270, 50));

        cmbDe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KiloGramo", "Tonelada", "Libra", "Onza" }));
        cmbDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeActionPerformed(evt);
            }
        });
        bgMasas.add(cmbDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 330, 50));

        cmbA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KiloGramo", "Tonelada", "Libra", "Onza" }));
        cmbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAActionPerformed(evt);
            }
        });
        bgMasas.add(cmbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, 50));

        btnButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtButton.setText("CONVERTIR");
        txtButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnButtonLayout = new javax.swing.GroupLayout(btnButton);
        btnButton.setLayout(btnButtonLayout);
        btnButtonLayout.setHorizontalGroup(
            btnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnButtonLayout.setVerticalGroup(
            btnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgMasas.add(btnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 330, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechas-hacia-arriba-y-hacia-abajo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bgMasas.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 50, 50));

        valorConvertido.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        valorConvertido.setForeground(new java.awt.Color(51, 51, 51));
        valorConvertido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorConvertido.setText("12");
        bgMasas.add(valorConvertido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 330, 50));

        add(bgMasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed

    }//GEN-LAST:event_ValorActionPerformed

    private void cmbDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDeActionPerformed

    private void cmbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAActionPerformed

    private void txtButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtonMouseClicked
        String valorTxt = Valor.getText();
        double valor = Double.parseDouble(valorTxt);
        String deTxt = cmbDe.getSelectedItem().toString();
        String aTxt = cmbA.getSelectedItem().toString();

        double resultado = Logica.conversorMasas(deTxt, aTxt, valor);
        String resultadoTxt = Double.toString(redondear(resultado));
        valorConvertido.setText(resultadoTxt);
    }//GEN-LAST:event_txtButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Logica.cambiarOpciones(cmbDe, cmbA);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Valor;
    private javax.swing.JPanel bgMasas;
    private javax.swing.JPanel btnButton;
    private javax.swing.JComboBox<String> cmbA;
    private javax.swing.JComboBox<String> cmbDe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtButton;
    private javax.swing.JLabel valorConvertido;
    // End of variables declaration//GEN-END:variables
}
